### ISSUE TITLE
Custom port instead of 80

### ISSUE THREAD

**Issue by schklom** [spotweb/spotweb#769]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when multiple Docker containers try to share the same inner port.
Spotweb uses port 80, and this conflicts with another container.

**Describe the solution you'd like**
An option to customize the default port, I think `ownsettings.php` would be good for that.

**Describe alternatives you've considered**
Another vpn container.
A reverse proxy behind the vpn container.

Both options are extra CPU burden.

**Additional context**
Here is the docker-compose.yml that I want to use, but can't
```yaml
services:

  vpn:
    image: ...
    ports:
      - 8000:80 # Spotweb
      - 8001:80 # Container1
  
  container1: # Exposes port 80
    image: ...
    network_mode: service:vpn

  spotweb: # Exposes port 80
    image: ...
    network_mode: service:vpn
```
because one of the containers does not get routed to (i think the latest container created is the one that gets routed to).

**Comment by Sweepr** [comment]
I am not familiar with Docker, have you tried to contact the developer of the docker image for help regarding this?

For all i can find quickly it must be possible to run multiple docker images using the same inner port 80.

https://docs.docker.com/config/containers/container-networking/
https://stackoverflow.com/questions/58449359/why-multiple-docker-containers-can-have-the-same-internal-port
https://stackoverflow.com/questions/31822862/how-to-host-two-docker-containers-exposing-port-80-on-the-same-server

**Comment by mesa57** [comment]
I have jgeusenbroek/spotweb docker image in test setup and no problems assigning port 80 to any other unused port on the host.

**Comment by schklom** [comment]
> have you tried to contact the developer of the docker image for help regarding this?

I read a little but cannot figure it out: is port 80 hardcoded on your end? If yes, this is a Spotweb issue, not a Docker image issue.
Otherwise, I will leave you alone and contact the developer of the Docker image :)

> it must be possible to run multiple docker images using the same inner port 80

Yes, but when they are networked through another container, that container redirects all inner ports to the corresponding containers. And when there are many sharing the same inner port, the redirection gets messed up.
The situation is similar to multiple servers being exposed on port 80 at the same time.

**Comment by schklom** [comment]
@mesa57 
> no problems assigning port 80 to any other unused port on the host

That is because you are assigning it on the host.
Try to have 2 servers with inner port 80 and network them behind another container like I did. One of the two will not be available.

```yaml
services:

  vpn:
    image: hello-world
    ports: # Either Spotweb or Whoami is not accessible
      - 8000:80 # Spotweb
      - 8001:80 # Whoami
  
  spotweb: # Inner port 80
    image: jgeusenbroek/spotweb
    network_mode: service:vpn

  whoami: # Inner port 80
    image: containous/whoami
    network_mode: service:vpn
```
