### ISSUE TITLE
Page duplicated in URLs

### ISSUE THREAD

**Issue by schklom** [spotweb/spotweb#770]
**Describe the bug/issue**
As soon as I access Spotweb on Docker behind a reverse-proxy, URLs become strange.
CSS is also not loaded because of it.

For example, the Settings page links look like `https://spotweb.example/page=editsettings/#editsettingstab-4`. Clicking on it leads me to a `404 Not Found` page.

In the Settings page, the URL `https://spotweb.example/page=editsettings/?page=statics&type=css&mod=1664463575` returns an error `404 Not Found` because it does not exist.

This does not happen when I access Spotweb directly with `http`.

**Have you searched the internet or Github for an answer?**
I can't find any other mention of this problem.

**To Reproduce**
```yaml
services:

  vpn:
    # Needs to be set up with a VPN configuration
    # https://github.com/qdm12/gluetun/wiki
    image: qmcgaw/gluetun
    ports:
      - 8000:80 # Spotweb

  spotweb:
    image: jgeusebroek/spotweb
    environment:
      TZ: Europe/Berlin
      SPOTWEB_DB_TYPE: pdo_pgsql
      SPOTWEB_DB_HOST: 127.0.0.1
      SPOTWEB_DB_PORT: 5432
      SPOTWEB_DB_NAME: spotweb
      SPOTWEB_DB_USER: spotweb
      SPOTWEB_DB_PASS: spotweb
    network_mode: service:vpn

  spotweb-db:
    image: postgres:15-alpine
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: spotweb
      POSTGRES_USER: spotweb
      POSTGRES_PASSWORD: spotweb
    network_mode: service:vpn
```

**Expected behavior**
I expect Spotweb to generate the same URLs with and without a reverse proxy.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian stable
 - Browser Firefox
 - Spotweb Version [e.g. 1.4.8]
 - Which branch Master
 - PHP version 8.0.23
 - Device information: Raspberry Pi

**Additional context**
The reverse proxy I use is HAProxy.
The only thing I do on it is pass the classical `X-Forwarded-*` headers (For, Host, URI, Proto), `X-SSL` with value `on`, and point to my Raspberry Pi on port 8000.
